version: "3"
services:
  spring-tpfoyer:
    image: malekchouaya/malekchouaya_g2_tpfoyer
    ports:
      - "8089:8089"
    networks:
      - foyerr
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/malekdata:/var/lib/mysql:rw
    networks:
      - foyerr
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
  front-kaddem:
    image: rakizouari/front
    ports:
      - "80:80"
    networks:
      - foyerr
    depends_on:
      - spring-tpfoyer
      - mysqldb

networks:
  foyerr: